# Generated by Django 2.0.4 on 2018-05-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_id', models.IntegerField(default=0, verbose_name='athlete_id')),
                ('athlete_name', models.CharField(max_length=20, verbose_name='athlete_name')),
            ],
        ),
    ]
