# Generated by Django 2.0.5 on 2018-05-27 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_name', models.CharField(choices=[('1', '7-8'), ('2', '9-10'), ('3', '11-12')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_name', models.CharField(max_length=20)),
                ('athlete_id_cardnumber', models.CharField(max_length=20, verbose_name='id card number')),
                ('athlete_sex', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=6)),
                ('athlete_age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.AgeGroup')),
            ],
        ),
        migrations.CreateModel(
            name='FinalScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score_Type', models.CharField(choices=[('PCS', 'preliminary competition scores'), ('FCS', 'final competition scores')], max_length=3)),
                ('Score_Value', models.CharField(max_length=5)),
                ('Reward_Point', models.CharField(max_length=5)),
                ('Punish_Point', models.CharField(max_length=5)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='sports.Athlete')),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Judge_name', models.CharField(max_length=20)),
                ('Judge_id_cardnumber', models.CharField(max_length=20, verbose_name='id card number')),
                ('Judge_Phonenumber', models.CharField(max_length=11, verbose_name='phone number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(default=0)),
                ('group_number', models.IntegerField(default=0)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='sports.Athlete')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_name', models.CharField(choices=[('1', '单杠'), ('2', '双杠'), ('3', '吊环'), ('4', '跳马'), ('5', '自由体操'), ('6', '鞍马'), ('7', '蹦床'), ('8', '高低杠'), ('9', '平衡木')], max_length=4)),
                ('Project_sex', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=2)),
                ('Project_agegroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.AgeGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score_Type', models.CharField(choices=[('PCS', 'preliminary competition scores'), ('FCS', 'final competition scores')], max_length=3)),
                ('Score_Value', models.CharField(max_length=5)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='sports.Athlete')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='sports.Judge')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='sports.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_account_number', models.CharField(max_length=20, verbose_name='account number')),
                ('Team_account_password', models.CharField(max_length=20, verbose_name='account passward')),
                ('Team_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamDoctor_name', models.CharField(max_length=20)),
                ('TeamDoctor_id_cardnumber', models.CharField(max_length=20, verbose_name='id card number')),
                ('TeamDoctor_Phonenumber', models.CharField(max_length=11, verbose_name='phone number')),
                ('TeamDoctor_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamInstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamInstructor_name', models.CharField(max_length=20)),
                ('TeamInstructor_id_cardnumber', models.CharField(max_length=20, verbose_name='id card number')),
                ('TeamInstructor_Phonenumberv', models.CharField(max_length=11, verbose_name='phone number')),
                ('TeamInstructor_sex', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=2)),
                ('TeamInstructor_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamLeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeamLeader_name', models.CharField(max_length=20)),
                ('TeamLeader_id_cardnumber', models.CharField(max_length=10, verbose_name='id card number')),
                ('TeamLeader_Phonenumber', models.CharField(max_length=11, verbose_name='phone number')),
                ('TeamLeader_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Team')),
            ],
        ),
        migrations.AddField(
            model_name='participate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='sports.Project'),
        ),
        migrations.AddField(
            model_name='finalscore',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='sports.Project'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='athlete_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('athlete', 'project', 'judge')},
        ),
        migrations.AlterUniqueTogether(
            name='participate',
            unique_together={('athlete', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='finalscore',
            unique_together={('athlete', 'project')},
        ),
    ]
