# Generated by Django 2.0.4 on 2018-05-19 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score_Type', models.CharField(max_length=3)),
                ('Score_Value', models.CharField(max_length=5)),
                ('Reward_Point', models.CharField(max_length=5)),
                ('Punish_Point', models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='athlete',
            name='athlete_sex',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=6),
        ),
        migrations.AddField(
            model_name='finalscore',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='sports.Athlete'),
        ),
        migrations.AddField(
            model_name='finalscore',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.ProtectedError, to='sports.Project'),
        ),
        migrations.AlterUniqueTogether(
            name='finalscore',
            unique_together={('athlete', 'project')},
        ),
    ]
