# Generated by Django 2.0.4 on 2018-05-04 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField(default=0, verbose_name='team_id')),
                ('team_name', models.CharField(max_length=20, verbose_name='team_name')),
            ],
        ),
        migrations.AddField(
            model_name='athlete',
            name='Team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sports.Team'),
        ),
    ]
