# Generated by Django 2.0.5 on 2018-05-21 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_auto_20180519_1148'),
        ('sports', '0002_auto_20180519_2008'),
    ]

    operations = [
    ]
