# Generated by Django 2.0.5 on 2018-05-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_auto_20180512_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Project_name',
            field=models.CharField(choices=[('1', '单杠'), ('2', '双杠'), ('3', '吊环'), ('4', '跳马'), ('5', '自由体操'), ('6', '鞍马'), ('7', '蹦床'), ('8', '高低杠'), ('9', '平衡木')], max_length=4),
        ),
        migrations.AlterField(
            model_name='teaminstructor',
            name='TeamInstructor_sex',
            field=models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=2),
        ),
    ]
