# Generated by Django 2.0.4 on 2018-05-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_auto_20180505_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='Team',
            new_name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='team_money',
            field=models.IntegerField(default=1000, verbose_name='team_money'),
        ),
    ]
