# Generated by Django 2.0.5 on 2018-05-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_auto_20180512_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agegroup',
            name='age_name',
            field=models.CharField(choices=[('1', '7-8'), ('2', '9-10'), ('3', '11-12')], max_length=2),
        ),
    ]
